import { SavedUser } from '@/typed'
import Header from './components/Header'
import Providers from './components/Providers'
import './globals.css'
import { Nunito } from 'next/font/google'
import { getCurrentUser } from './libs/getCurrentUser'
import LoginModal from './components/LoginModal'
import RegisterModal from './components/RegisterModal'
import RentModal from './components/RentModal'
import SearchModal from './components/SearchModal'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Airbnb-clone',
  description: 'Generated by Pavlo Kozak',
  icons: {
    icon: 'https://cdn0.iconfinder.com/data/icons/picons-social/57/68-airbnb-512.png',
    shortcut: 'https://cdn0.iconfinder.com/data/icons/picons-social/57/68-airbnb-512.png',
  },
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const currentUser: SavedUser | null = await getCurrentUser()

  return (
    <html lang="en">
      <body className={nunito.className}>
        <Providers>
          <Header currentUser={currentUser} />
          <LoginModal />
          <RegisterModal />
          <RentModal />
          <SearchModal />
          {children}
        </Providers>
      </body>
    </html>
  )
}
